config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :users, :products, :blogs
  end

  resources :products, except: [:edit]
  
  resources :blogs do
    resources :comments
  end

  resources :pages do
    collection do
      post :url_preview
    end
  end

  resources :pages do
    resources :pagecomments
  end  

  namespace :admin do
    resources :products do 
      resources :images
    end
  end

  get 'users/index'

  get 'pages/show'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "pages#index"

  match '*path', to: redirect('/404'), via: :all
 
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :post, presence: true
  validates :content, presence: true

  mount_uploaders :images, ImageUploader

  has_many :comments, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :references
  has_many :product, through: :references
  validates_length_of :name, :minimum=>3, :too_short => "Please enter at least 3 character"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog

  validates_length_of :name, :minimum=>3, :too_short => "Please enter at least 3 character"
  validates_length_of :body, :minimum=>10, :too_short => "Please enter at least 10 character"
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/page.rb
require 'open-uri'
require 'nokogiri'

class Page < ApplicationRecord
  
  has_many :pagecomments

  def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super
  end

  def self.parse_url(url)
    doc = Nokogiri::HTML(open(url), nil, 'UTF-8')
    rs = {}
    title = ""
    description = ""
    url = ""
    image_url = ""

    doc.xpath("//head//meta").each do |meta|
    if meta['property'] == 'og:title'
    title = meta['content']
    elsif meta['property'] == 'og:description' || meta['name'] == 'description'
    description = meta['content']
    elsif meta['property'] == 'og:url'
    url = meta['content']
    elsif meta['property'] == 'og:image'
    image_url = meta['content']
    end
    end

    if title == ""
    title_node = doc.at_xpath("//head//title")
    if title_node
    title = title_node.text
    elsif doc.title
    title = doc.title
    else
    title = url
    end
    end

    if description ==""
    #maybe search for content from BODY
    description = title
    end

    if url ==""
    url = url
    end


    rs[:title] = title 
    rs[:description] = description
    rs[:url] = url
    rs[:image_url] = image_url

    rs
  end
end


  

app/models/pagecomment.rb
class Pagecomment < ApplicationRecord
  belongs_to :page

  validates_length_of :name, :minimum=>3, :too_short => "Please enter at least 3 character"
  validates_length_of :body, :minimum=>10, :too_short => "Please enter at least 10 character"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :references
  has_many :product, through: :references
  validates_length_of :name, :minimum=>3, :too_short => "Please enter at least 3 character"

  mount_uploaders :images, ImageUploader

end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
  class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
          authentication_keys: [:username]
  mount_uploader :image, AvatarUploader
         
  ROLES = ["admin", "user"]
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def admin?
    role == "admin"
  end

  def user?
    role == "user"
  end

  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.paginate(:page => params[:page], :per_page => 3)
  end

  def show
    @blog = Blog.find(params[:id])
    
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    authorize @blog
    @blog = Blog.find(params[:blog_id])
    
    @comment = @blog.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @blog }
        format.js
      else
        format.html { redirect_to @blog }
        format.js
      end
    end
  end

  def destroy
    authorize @blog
    @blog = Blog.find(params[:blog_id])
    
    @comment = @blog.comments.find(params[:id])
    @comment.destroy

    redirect_to blog_path(@blog)
  end

  private 
  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:create]
  before_action :set_page, only: [:show, :edit, :update, :destroy]
  def show
    @page = Page.find params[:id]
    @pagecomment = @page.pagecomments.new
    respond_to do |format|
        format.html
        format.json { render json: @page.to_json} 
    end
  end

  def url_preview
    url = params[:url]
    @rs = Page.parse_url(url)
    respond_to do |format|
      format.html
      format.json { render json: @rs} 
    end 
  end

  def index
    @pages = Page.paginate(:page => params[:page], :per_page => 3)
  end

  def create
  end

  def new
    puts params
    
    @page = Page.new(page_params)
    @page.save
    
    respond_to do |format|
      format.html { }  
      format.json { render json: {data: "success"} }
      
    end
  end

  def destroy
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private

    def page_params
      params.require(:page).permit(:title, :content, :image_url)
    end

    def set_page
      @page = Page.find_by id: params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/page_comments_helper.rb
module PageCommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/admin_applications.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/navigation-admin" %>
    <div class="container">
    <% if current_user.try(:username).nil? %>
  <div></div>
  <% else %>
  <h1> Hi <%= current_user.try(:username) %></h1>
  <% end %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
 
  <div class="container main">
    <%= yield %>
  </div>
 
 <%= render "shared/footer-admin" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "shared/navigation" %>
  <div class="container">
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
 
  <div class="container main">
    <%= yield %>
  </div>
 
 <%= render "shared/footer" %>
</body>
</html>

app/views/pages/index.html.erb
<% if current_user.try(:username).nil? %>
 <div></div>
<% else %>
 <h1> Hi <%= current_user.try(:username) %></h1>
<% end %>
<div class="form-group preview">
<%= form_tag url_preview_pages_path do  %>
<%= text_field_tag :image_remote_url, "", class: "form-control", placeholder: "Post your link here"%>
<% end %>
</div>
<pre>
  <div id="url_preview"></div>
  <div id="title_preview"></div>
  <div id="image_preview"></div>
  <p id="description_preview"></p>
</pre>



<a class="btn btn-primary" id="sub-db" data-url="/pages/new" href="javascript:void(0)"> POST THIS LINK </a>
  <% if  flash[:errors].present? %>
  <div class="alert alert-danger">
    <%= flash[:errors] %>
  </div>
<% end %>
<table class="table table-striped">
    <thead>
      <tr>
        <th class="text-center">Title</th>
        <th class="text-center">Image</th>
        <th class="text-center">Description</th>
        <th>View</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <% @pages.each do |page| %>
        <td><%= page.title %></td>
        <td class="text-center"><%= image_tag(page.image_url, :class => 'list_image') if page.image_url.present? %></td>
        <td ><%= truncate(page.content, :length => 80) %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-search"></i>'.html_safe, page_path(page), class: "btn btn-primary btn-xs"%> </td>
        <% if current_user.try(:role) == "admin" %>
        <td> <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, page_path(page), data: { confirm: 'Are you sure?' },
                    :method => :delete, class: "btn btn-danger btn-xs" %></td>
        <% end %>            
      </tr>
      <% end %>
    </tbody>
  </table>

  <p><%= will_paginate @pages %></p>

  
        

app/views/pages/show.html.erb
<div class="container  text-center">
<p>
  <strong>Post:</strong>
  <%= @page.title %>
</p>
<p>
  <%= image_tag @page.image_url, class: "detail-images" %>
</p>
<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>
<br>
</div>
<div class="container">
<h2> <%= @page.pagecomments.count %> Comments</h2>
<h3> Add a Comments: </h3>
        <%= render 'pagecomments/form' %> 
  
        <%= render 'pagecomments/pagecomments'  %>
        
<br>
</div>

app/views/pages/view.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">
  <%= @page.post %>
</h1>

<p class="text-center">
  <% @page.images.each do |image| %>
    <%= image_tag image, class: "detail-images" %>
  <% end %> <br/>
</p>

<p>
  <%= @page.content %>
</p>

<br/>
<h3>Add a comment:</h3>
<h2> <%= @page.comments.count %> Comments </h2>
  <%= render 'comments/form' %> <br/>
  <%= render @page.comments %> <br/>
<br/>

<%= link_to 'Back', pages_path %>

app/views/shared/_footer-admin.html.erb
<footer class="page-footer admin">

  <!-- Copyright -->
  <div class="footer-copyright text-center">Webmely © 2018
  Intermediate Project
  </div>
  <!-- Copyright -->

</footer>

app/views/shared/_footer.html.erb
<footer class="page-footer">

  <!-- Copyright -->
  <div class="footer-copyright text-center">Webmely © 2018
  Intermediate Project
  </div>
  <!-- Copyright -->

</footer>

app/views/shared/_navigation-admin.html.erb
<nav class="navbar navbar-inverse admin">
  <div class="container">
    <div class="navbar-header">
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', admin_users_path %></li>
        <li><%= link_to 'Products Management', admin_products_path %></li>
        <li><%= link_to 'Users Management', admin_users_path %></li>
        <li><%= link_to 'Blogs Management', admin_blogs_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
        <%= image_tag(current_user.image_url(:thumb), class: "user-avatar") if current_user.image.present? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
        <li> <%= link_to "English", locale: "en", class: "btn btn-default"%> </li>
        <li> <%= link_to "VietNam", locale: "vi", class: "btn btn-default"%> </li>
      </div>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse ">
  <div class="container">
    <div class="navbar-header">
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to 'Blogs', blogs_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
        <%= image_tag(current_user.image_url(:thumb), class: "user-avatar") if current_user.image.present? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
           <li> <%= link_to "English", locale: "en", class: "btn btn-default"%> </li>
           <li> <%= link_to "VietNam", locale: "vi", class: "btn btn-default"%> </li>
      </ul>
    </div>
  </div>
</nav>