config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :users, :products, :blogs
  end

  resources :products, except: [:edit]
  
  resources :blogs do
    resources :comments
  end

  resources :pages do
    collection do
      post :url_preview
    end
  end

  resources :pages do
    resources :pagecomments
  end  

  namespace :admin do
    resources :products do 
      resources :images
    end
  end

  get 'users/index'

  get 'pages/show'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "pages#index"

  match '*path', to: redirect('/404'), via: :all
 
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
 end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :references
  has_many :product, through: :references
  validates_length_of :name, :minimum=>3, :too_short => "Please enter at least 3 character"

  mount_uploaders :images, ImageUploader

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  layout "admin_applications"

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    authorize @products
    @products = Product.paginate(:page => params[:page], :per_page => 3)
  end

  def show
  end

  # GET /products/new
  def new
    authorize @product
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    authorize @product
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize @product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # def delete_picture
  #   respond_to do |format|
  #     @i = params[:i].to_i
  #     if @i != 0
  #       remain_images = @product.images # copy initial avatars
  #       delete_image = remain_images.delete_at(@i) # delete the target image
  #       delete_image.try(:remove!) # delete image
  #       @product.images = remain_images # re-assign back
  #       @product.save  

  #       format.html { redirect_to admin_product_path, alert: 'Test' }
  #       format.json { head :no_content }@product = Product.new(product_params
  #     else
  #       format.html { redirect_to admin_@product = Product.new(product_paramsast 1 image' }
  #       format.json { head :no_content }@product = Product.new(product_params
  #     end
  #   end
  # end

  # def delete_picture
  #   respond_to do |format|
  #     @i = params[:i].to_i
  #     if @i != 0
  #       remain_images = @product.images # copy initial avatars
  #       delete_image = remain_images.delete_at(@i) # delete the target image
  #       delete_image.try(:remove!) # delete image
  #       @product.images = remain_images # re-assign back
  #       @product.save  

  #       format.html { redirect_to admin_product_path, alert: 'Test' }
  #       format.json { head :no_content }
  #     else
  #       format.html { redirect_to admin_product_path, alert: 'Product has at least 1 image' }
  #       format.json { head :no_content }
  #     end
  #   end
  # end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize @product
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :slug, {images: []})
    end
end

app/controllers/products_controller.rb
class ProductsController < ::ApplicationController
  before_action :set_product, only: [:show]
  before_action :authenticate_user!
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(:page => params[:page], :per_page => 3)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @products = Product.all
  end

  # # GET /products/new
  # def new
  #   @product = Product.new
  # end

  # # GET /products/1/edit
  # def edit
  # end

  # # POST /products
  # # POST /products.json
  # def create
  #   @product = Product.new(product_params)
  #   respond_to do |format|
  #     if @product.save
  #       format.html { redirect_to admin_products_path, notice: 'Product was successfully created.' }
  #       format.json { render :show, status: :created, location: @product }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @product.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /products/1
  # # PATCH/PUT /products/1.json
  # def update
  #   respond_to do |format|
  #     if @product.update(product_params)
  #       format.html { redirect_to admin_products_path, notice: 'Product was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @product }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @product.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /products/1
  # # DELETE /products/1.json
  # def destroy
  #   @product.destroy
  #   respond_to do |format|
  #     format.html { redirect_to admin_products_path, notice: 'Product was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  # def delete_picture
  #   respond_to do |format|
  #     @i = params[:i].to_i
  #     if @i != 0
  #       remain_images = @product.images # copy initial avatars
  #       delete_image = remain_images.delete_at(@i) # delete the target image
  #       delete_image.try(:remove!) # delete image
  #       @product.images = remain_images # re-assign back
  #       @product.save  

  #       format.html { redirect_to admin_product_path, alert: 'Test' }
  #       format.json { head :no_content }
  #     else
  #       format.html { redirect_to admin_product_path, alert: 'Product has at least 1 image' }
  #       format.json { head :no_content }
  #     end
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def product_params
  #     params.require(:product).permit(:name, :description, :slug, {images: []})
  #   end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<h3>Edit a product</h3>

<%= form_for([:admin, @product]) do |f| %> 
    <div class="form-group">
        <%= f.label :Product_name %><br>
        <%= f.text_field :name, placeholder: "Product Name", class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, :rows => 6, placeholder: "Product description", class: "form-control" %>
    </div>    

    <%= f.label :images %><br>
    <%= f.file_field :images, multiple: true %>

    <div class="form-group">
        <%= f.label :slug %><br>
        <%= f.text_field :slug, placeholder: "Slug", class: "form-control" %>
    </div>

    <div class="actions">
        <%= f.submit "Submit", class: "btn btn-primary" %>
        <%= link_to "Back", admin_products_path(product), class: "btn btn-primary" %>
    </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

app/views/admin/products/index.html.erb
<% if  flash[:errors].present? %>
  <div class="alert alert-danger">
    <%= flash[:errors] %>
  </div>
<% end %>
 <p> <%= I18n.t ".title" %> </p>
<table class="table table-striped">
    <thead>
      <tr>
        <th>Post</th>
        <th>Image</th>
        <th>Content</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <% @products.each do |product| %>
        <td><%= product.name %></td>
        <td><%= image_tag(product.images.first, :class => 'list_image') if product.images.present? %></td>
        <td><%= truncate(product.description, :length => 80) %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-search"></i>'.html_safe, admin_product_path(product), class: "btn btn-primary btn-xs"%> </td>
        <td> <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_admin_product_path(product), class: "btn btn-primary btn-xs" %></td>
        <td> <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, admin_product_path(product), data: { confirm: 'Are you sure?' },
                    :method => :delete, class: "btn btn-danger btn-xs" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <td> <%= link_to "New Post", new_admin_product_path, class: "btn btn-primary" %></td>
  
  <%= will_paginate @products, class: "pagination" %>
  

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @product.slug %>
</p>

<h3>Product Images</h3>
<table class="table table-striped">
    <thead>
      <tr>
        <th>No</th>
        <th>Image</th>
        <th>Image Replace</th>
        <th>Submit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <% @product.images.each_with_index do |image, i| %>
        <td><%= i+1 %></td>
        <td><%= image_tag(image, :class => 'list_image')%></td>
        <%= form_tag admin_product_image_path(@product.id, i), method: :put, multipart: true  do %> 
          <td> <%= file_field_tag "image", class: "upload-image" %></td>
          <td> <%= button_tag "", type: "submit", class: "btn btn-primary glyphicon glyphicon-ok btn-xs submit-image", disabled: true %></td>
        <% end %>
        <td>
        <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe ,admin_product_image_path(@product , i), method: :delete, confirm: 'Delete?', class: "btn btn-danger btn-xs"%> </td>
      </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to 'Edit', edit_admin_product_path(@product), class: "btn btn-primary" %>
<%= link_to 'Back', admin_products_path, class: "btn btn-primary" %>

<script>


    $(document).ready(function(params) {
      $('.upload-image').on('change', function (e) { 
        if( ($(e.target).val() != "") ){
          console.log(1)
          $(e.target).closest('tr').find('.submit-image').attr('disabled', false);
        }else{
          
          $(e.target).closest('form').find('.submit-image').attr('disabled', true);
        }
        console.log(($(e.target)))
        console.log($(e.target).closest('form').find('.submit-image'))
       })
    })
</script>