config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :users, :products, :blogs
  end

  resources :products, except: [:edit]
  
  resources :blogs do
    resources :comments
  end

  resources :pages do
    collection do
      post :url_preview
    end
  end

  resources :pages do
    resources :pagecomments
  end  

  namespace :admin do
    resources :products do 
      resources :images
    end
  end

  get 'users/index'

  get 'pages/show'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "pages#index"

  match '*path', to: redirect('/404'), via: :all
 
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
 end
end

app/models/user.rb
  class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
          authentication_keys: [:username]
  mount_uploader :image, AvatarUploader
         
  ROLES = ["admin", "user"]
  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def admin?
    role == "admin"
  end

  def user?
    role == "user"
  end

  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  layout "admin_applications"
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to admin_users_path, alert: "User created successfully."
    else
      respond_to do |format|
        format.html { render :new }
      end
    end
  end

  def edit
    if current_user == @user || !@user.admin?
    else
      flash[:errors] = "Can not edit other admin profile"
      redirect_to admin_users_path
    end

  end

  def update
    if @user.update_attributes(user_params)
      redirect_to admin_users_path, alert: "User update successfully."
    else
      respond_to do |format|
        format.html { render :edit }
      end
    end
  end

  def show
  end
  
  def destroy 
    @user.destroy

    redirect_to admin_users_path, notice: "Delete success"
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :role, :password_confirmation, :image)    
  end

  def set_user
    @user = User.find_by id: params[:id]
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  def after_sign_in_path_for(resource)
    if resource.role == "admin"
      "/admin/users"
    else 
      "/"
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :email %>
    <%= f.text_field :email %>
    
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
    <%= f.label :role%>
    <%= f.select :role , User::ROLES%>
<% end %>

app/views/admin/users/edit.html.erb
<h2>Edit User</h2>
 
<%= form_for([:admin, @user]) do |f| %>

  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

     <%= f.label :role%>
    <%= f.select :role , User::ROLES, {prompt: 'Select Role'}, class: "form-control" %>
  <br/>

    <%= f.label :image %> <br />
    <%= image_tag @user.image %>
    <%= f.file_field :image, value: "Choose a file"  %>

  <div class="actions">
    <%= f.submit "Update", class: "btn btn-primary" %>
    <%= link_to "Back", admin_users_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<% if  flash[:errors].present? %>
  <div class="alert alert-danger">
    <%= flash[:errors] %>
  </div>
<% end %>
<table class="table table-striped">
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Role</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <% @users.each do |user| %>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td> <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_admin_user_url(user), class: "btn btn-primary btn-xs" %></td>
        <td> <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, admin_user_path(user), data: { confirm: 'Are you sure?' },
                    :method => :delete, class: "btn btn-danger btn-xs" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <td> <%= link_to "New User", "users/new", class: "btn btn-primary" %></td>



        

app/views/admin/users/new.html.erb
<h2>New User</h2>
 
<%= form_for([:admin, @user]) do |f| %>
  <%= @user.errors.full_messages %>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: "form-control" %>
  </div>
 
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>
 
  <div class="form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
  </div>
 
  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
  </div>
  
    <%= f.label :role%>
    <%= f.select :role , User::ROLES, {prompt: 'Select Role'}, class: "form-control" %>
  <br/>

  <%= f.label :image %> <br />
    <%= image_tag @user.image %>
    <%= f.file_field :image, value: "Choose a file"  %>
  
 
  <div class="actions">
    <%= f.submit "Sign up", class: "btn btn-primary" %>
    <%= link_to "Back", admin_users_path, class: "btn btn-primary" %>
  </div>

<% end %>
 