config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    resources :users, :products, :blogs
  end

  resources :products, except: [:edit]
  
  resources :blogs do
    resources :comments
  end

  resources :pages do
    collection do
      post :url_preview
    end
  end

  resources :pages do
    resources :pagecomments
  end  

  namespace :admin do
    resources :products do 
      resources :images
    end
  end

  get 'users/index'

  get 'pages/show'

  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: "pages#index"

  match '*path', to: redirect('/404'), via: :all
 
  if Rails.env.production?
    get '404', :to => 'application#page_not_found'
 end
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :post, presence: true
  validates :content, presence: true

  mount_uploaders :images, ImageUploader

  has_many :comments, dependent: :destroy
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < Admin::BaseController
  layout "admin_applications"
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.paginate(:page => params[:page], :per_page => 3)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    respond_to do |format|
      if @blog.save
        format.html { redirect_to admin_blogs_path, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end    
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to admin_blogs_path, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end  
  end

  def edit
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to admin_blogs_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show
  end

  private

  def blog_params
    params.require(:blog).permit(:post, :content, {images: []})
  end
  
  def set_blog
  @blog = Blog.find_by id: params[:id]
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.paginate(:page => params[:page], :per_page => 3)
  end

  def show
    @blog = Blog.find(params[:id])
    
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/admin/blogs/edit.html.erb
<h3>Edit a blog</h3>

<%= form_for([:admin, @blog]) do |f| %>
  <%= @blog.errors.full_messages %>

  <div class="form-group">
    <%= f.label :post %><br />
    <%= f.text_field :post, placeholder: "Post", class: "form-control" %>
  </div>
 
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "ckeditor", cols: 20, rows: 20 %>
  </div>

  <div class="form-group">
        <%= f.label :images %><br>
        <%= f.file_field :images, multiple: true %>
    </div>
 
  <div class="actions">
    <%= f.submit "Update", class: "btn btn-primary" %>
    <%= link_to "Back", admin_blogs_path, class: "btn btn-primary" %>
  </div>

<% end %>
 

app/views/admin/blogs/index.html.erb
<% if  flash[:errors].present? %>
  <div class="alert alert-danger">
    <%= flash[:errors] %>
  </div>
<% end %>
 <p> <%= I18n.t ".title" %> </p>
<table class="table table-striped">
    <thead>
      <tr>
        <th>Post</th>
        <th>Image</th>
        <th>Content</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <tr>
      <% @blogs.each do |blog| %>
        <td><%= blog.post %></td>
        <td><%= image_tag(blog.images.first, :class => 'list_image') if blog.images.present? %></td>
        <td><%= truncate(blog.content, :length => 80) %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-search"></i>'.html_safe, admin_blog_path(blog), class: "btn btn-primary btn-xs"%> </td>
        <td> <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_admin_blog_path(blog), class: "btn btn-primary btn-xs" %></td>
        <td> <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, admin_blog_path(blog), data: { confirm: 'Are you sure?' },
                    :method => :delete, class: "btn btn-danger btn-xs" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <td> <%= link_to "New Post", new_admin_blog_path, class: "btn btn-primary" %></td>
  <p><%= will_paginate @blogs %></p>

app/views/admin/blogs/new.html.erb
<h3>Create a blog</h3>

<%= form_for([:admin, @blog]) do |f| %>
  <%= @blog.errors.full_messages %>

  <div class="form-group">
    <%= f.label :post %><br />
    <%= f.text_field :post, placeholder: "Post", class: "form-control" %>
  </div>
 
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "ckeditor" %>
  </div>

  <div class="form-group">
        <%= f.label :images %><br>
        <%= f.file_field :images, multiple: true %>
    </div>
 
  <div class="actions">
    <%= f.submit "Post", class: "btn btn-primary" %>
    <%= link_to "Back", admin_blogs_path, class: "btn btn-primary" %>
  </div>

<% end %>
 

app/views/admin/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="form-group">
  <strong>Post:</strong>
  <%= @blog.post %>
</div>

<div class="form-group">
<% @blog.images.each do |image| %>
  <%= image_tag image, class: "detail-images" %>
<% end %>
</div>

<div class="form-group">
  <strong>Content:</strong>
  <%= @blog.content.html_safe %>
  </div>


<%= link_to 'Edit', edit_admin_blog_path(@blog), class: "btn btn-primary" %>
<%= link_to 'Back', admin_blogs_path, class: "btn btn-primary" %>